on: [push]

jobs:
  fteqcc_job:
    runs-on: ubuntu-latest
    name: Build quakec sources
    steps:
      - name: Hello world action step
        id: qccbuild
        uses: Paizo/qcc-docker-action@1
      - name: Get the output time
        run: echo "The build output was ${{ steps.qccbuild.outputs.qcclogs }}"
