on:
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'

jobs:
  fteqcc_job:
    runs-on: ubuntu-latest
    name: Build quakec sources
    steps:
      - name: Hello world action step
        id: qccbuild
        uses: Paizo/qcc-docker-action@0.0.5
      - name: pwdlogs
        run: echo "pwdlogs was ${{ steps.qccbuild.outputs.pwdlogs }}"
      - name: lslogs
        run: echo "lslogs was ${{ steps.qccbuild.outputs.lslogs }}"
      - name: QCC logs
        run: echo "The build output was ${{ steps.qccbuild.outputs.qcclogs }}"
