on:
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
jobs:
  build_quake_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Build QC sources
        run: ./buildscripts/fteqcc64 -srcfile qc/progs.src
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: q1paizo
          path: |
            progs.dat
            PROGS/**/*.MDL
            MAPS/**/*.BSP
            SOUND/**/*.WAV

            
# jobs:
#   fteqcc_job:
#     runs-on: ubuntu-latest
#     name: Build quakec sources
#     steps:
#       - name: Hello world action step
#         id: qccbuild
#         uses: Paizo/qcc-docker-action@0.0.7
      # - name: pwdlogs
      #   run: echo "pwdlogs was ${{ steps.qccbuild.outputs.pwdlogs }}"
      # - name: lslogs
      #   run: echo "lslogs was ${{ steps.qccbuild.outputs.lslogs }}"
      # - name: QCC logs
      #   run: echo "The build output was ${{ steps.qccbuild.outputs.qcclogs }}"
